### ISSUE TITLE
feat: screen brightness and volume control by opencv

### ISSUE THREAD

**Issue by akashlogics** [Aryan-Chharia/Computer-Vision-Projects#1]
I created a project in Python using OpenCV to control screen brightness and volume control by our hands and I made this for my learning process now I would like to add it in this repository so others can learn from it 

So,can you please assign me this issue and label this as gssoc24-extd and hacktoberfest

**Comment by Aryan-Chharia** [comment]
Go Ahead!

**Comment by akashlogics** [comment]
can i get it level 2 as I adding two features

**Comment by Bhavya445** [comment]
can u plss assign this to me

**Comment by akashlogics** [comment]
> can u plss assign this to me

you can rise new issues of your own ideas

**Comment by Dwukn** [comment]
@Aryan-Chharia  can you assign me this issue
