### ISSUE TITLE
LUNG CANCER DETECTION

### ISSUE THREAD

**Issue by ramana2074** [Aryan-Chharia/Computer-Vision-Projects#105]
I would like to  build a classifier using a simple Convolution Neural Network which can classify normal lung tissues from cancerous. Lung cancer is a type of cancer that starts when abnormal cells grow in an uncontrolled way in the lungs.
please assign me?

**Comment by Aryan-Chharia** [comment]
already included in repo. check #85

**Comment by ramana2074** [comment]
okay sorry you may close this.
