### ISSUE TITLE
Real-time Boxer Detection and Tracking using Computer Vision| New Project

### ISSUE THREAD

**Issue by Nikhat623446** [Aryan-Chharia/Computer-Vision-Projects#107]
Hey @Aryan-Chharia I would like to contribute more to the repository by adding one of the advanced Real-time Boxer Detection and Tracking Project! Please let me know if I should start working on it and contribute more to this wonderful repository!

**Comment by Aryan-Chharia** [comment]
Hi @Nikhat623446, can you explain more in detail what this project is all about ?
