### ISSUE TITLE
Barcode/QR Code Based Authenticator Using OpenCV

### ISSUE THREAD

**Issue by 09viv** [Aryan-Chharia/Computer-Vision-Projects#109]
Hi @Aryan-Chharia 

Description
This project implements an authentication system using QR code scanning, leveraging OpenCV for image detection and pyzbar for decoding. The authenticator allows users to scan QR codes that contain unique identifiers, which are then verified against stored valid tokens for user authentication. The project focuses on real-time QR code scanning and backend logic for validating scanned data, without generating the QR codes.

### Features
1. **Real-time Scanning:** Scan codes using OpenCV and decode with `pyzbar`.
2. **User Authentication:** Verify extracted data against valid tokens.
3. **Secure Data Handling:** Encrypt sensitive data and prevent unauthorized access.
4. **User Interface:** Simple UI for code scanning with Flask backend.

Please assign me this issue under GSSOC'24 extd.

**Comment by Aryan-Chharia** [comment]
#55
