### ISSUE TITLE
Drawing Air Canvas with Mediapipe and Computer Vision

### ISSUE THREAD

**Issue by rithvikreddybasani** [Aryan-Chharia/Computer-Vision-Projects#115]
Hey @Aryan-Chharia I want to develop this project ,

**Project Description**
Allows users to paint using hand gestures via a camera or uploaded image. It tracks the user's hand movements using Mediapipe's hand-tracking, letting them draw in different colors on a canvas. Users can switch colors, clear the canvas, and use the app interactively.

**Comment by Aryan-Chharia** [comment]
is your project same as #31 ?

**Comment by rithvikreddybasani** [comment]
Yes . But a little bit different
