### ISSUE TITLE
Emotion Detection + Pose Detection using OpenCV ,MediaPipe ,DeepFace

### ISSUE THREAD

**Issue by akashlogics** [Aryan-Chharia/Computer-Vision-Projects#128]
# Emotion Detection + Pose Detection

It can be used to check for violence in any area with the help of CCTV Cameras. Violence is an urgent public health problem. From infants to the elderly, it affects people in all stages of life and can lead to a lifetime of physical, emotional, and economic problems.

### Libraries Used:
- OpenCV
- MediaPipe
- DeepFace
<img width="1440" alt="sample outputs" src="https://github.com/user-attachments/assets/c9902808-7d00-4bd5-8d57-50f904291e9d">

**Comment by Aryan-Chharia** [comment]
Already an issue and pose detection is in the repo
