### ISSUE TITLE
Real time road lane detection for Autonomous self driving vehicles using OpenCV

### ISSUE THREAD

**Issue by pranavvb03** [Aryan-Chharia/Computer-Vision-Projects#131]
Road lane detection is a critical component of the perception system in autonomous self-driving vehicles. The goal of this project is to identify and track lane markers on the road in real-time, helping the vehicle stay centered in its lane, avoid lane departures, and make safe driving decisions. Using OpenCV, lane detection can be implemented efficiently by processing video feeds from vehicle-mounted cameras.

**Comment by Aryan-Chharia** [comment]
Already an issue
