### ISSUE TITLE
Animal Identificaiton model using computer vision

### ISSUE THREAD

**Issue by 17arindam** [Aryan-Chharia/Computer-Vision-Projects#139]
I want to add a animal identificaion model which can be used to identify the animal with the help of computer vision 

- [ ] 
![Screenshot 2024-10-09 043408](https://github.com/user-attachments/assets/8bf97791-665f-4196-a218-145c8c8d2b5f)

**Comment by 17arindam** [comment]
@Aryan-Chharia please assign me this issue

**Comment by Aryan-Chharia** [comment]
Similar to Dog Breed. Not requried
