### ISSUE TITLE
Image Watermarking System

### ISSUE THREAD

**Issue by 09viv** [Aryan-Chharia/Computer-Vision-Projects#143]
Hi @Aryan-Chharia 

Description
The Image Watermarking System is a web-based application designed to allow users to upload images and apply custom watermarks (text or logo) for copyright protection and ownership marking. Built with **Flask** and **OpenCV**, this project enables users to personalize their watermark in terms of size, opacity, position, and more. The system provides an interactive interface for real-time preview and allows users to download the final watermarked images.

Key Features:
1. **Image Upload**: Users can upload images in various formats (JPG, PNG, etc.).
2. **Custom Watermark**: Add a watermark as text or a logo.
3. **Position Control**: Select the placement of the watermark (e.g., bottom-right, top-left).
4. **Adjustable Opacity**: Control the transparency of the watermark (0.1 to 1.0).
5. **Real-time Preview**: Instantly see how the watermark looks before downloading the final image.
6. **Download Watermarked Image**: After applying the watermark, users can download the modified image.
7. **User-friendly Interface**: Simple HTML form with options for watermark customization.

Please assign me this issue undern GSSOC'24 exts

**Comment by Megha-Malviya** [comment]
I will be using Python and OpenCV. To begin, I'll set up my development environment by installing OpenCV and NumPy. Once that's ready, I'll load the main image that I want to watermark along with the watermark image itself.

After that, I’ll resize the watermark to make sure it fits nicely on the main image, probably positioning it in the bottom-right corner. It's important to me that the watermark blends well with the background, so I’ll adjust its transparency to ensure it remains visible but doesn't overpower the original image. To do this, I’ll use NumPy to blend the pixel values of both images according to the level of transparency I choose.

Once I’ve applied the watermark successfully, I’ll save the new image with the watermark to my computer and then display it using OpenCV. Overall, I believe this project will effectively protect images with a watermark, making it clear who owns them while still keeping the original image looking great.
