### ISSUE TITLE
feat: dedecting object by colour HSV 

### ISSUE THREAD

**Issue by akashlogics** [Aryan-Chharia/Computer-Vision-Projects#144]
# Tracking Using HSV 
In this Example i tried to track objects with blue colors .(Blue is life :sunglasses:).

I used Trackbars to manipulate the values for blue range ,the following results are expressed interms of lowerValue(71,112,112) up to (255,255,255) .
#### Required Modules :
  - Numpy   
    ```bash
      pip install numpy
    ```
  - Opencv   
    ```bash
      pip install opencv-python
    ```
#### Results : 
![HSV_Results](https://github.com/user-attachments/assets/87d1b4b3-bce3-4674-b035-b7bb71e79cda)

**Comment by Aryan-Chharia** [comment]
Not interesting
