### ISSUE TITLE
Emtion detection

### ISSUE THREAD

**Issue by PiyushVIT346** [Aryan-Chharia/Computer-Vision-Projects#150]
i want to raise a new issue for emotion detection of human. Process I will follow: 

1. The haarcascade method is used to detect faces in each frame of the webcam feed.

2. The region of image containing the face is resized to 48x48 and is passed as input to the CNN.

3. The network outputs a list of softmax scores for the seven classes of emotions.

4. The emotion with maximum score is displayed on the screen.

Kindly assign this to me.

**Comment by Aryan-Chharia** [comment]
Already an issue
