### ISSUE TITLE
Lane Detection Using OpenCV

### ISSUE THREAD

**Issue by aviralgarg05** [Aryan-Chharia/Computer-Vision-Projects#156]
Use OpenCV and Machine Learning to detect lanes for autonomous vehicles.
I am a GSSOC'24 Extended and Hacktoberfest Contributor

**Comment by Aryan-Chharia** [comment]
go ahead

**Comment by INGEMINI** [comment]
I would like to work on this issue. Kindly assign me under GSSoC Ext 2024  Thank you!

**Comment by Absk024** [comment]
i would like to contribute @Aryan-Chharia

**Comment by Aryan-Chharia** [comment]
@Absk024 go ahead

**Comment by SimranShaikh20** [comment]
@Aryan-Chharia assign me this issue !
