### ISSUE TITLE
Terrain Classification Using Transfer learning

### ISSUE THREAD

**Issue by DarshAgrawal14** [Aryan-Chharia/Computer-Vision-Projects#158]
hey @Aryan-Chharia 
I am Darsh Agrawal , a fellow contributor and I would like to contribute by using Transfer learning and create a model to help various agencies label captured terrain images like mountains, coast , desserts etc . By using transfer learning we can use pre trained models like RESNET or Efficientnet and hyperparameter tune them for terrain classification for better accuracy when compared to traditional CNN models.

Keys features :
- Data Augmentation to handle rotated images
- Handle images with filters
- Transfer Learning for better classification accuracy
-  Low Inferencing time , handles large datasets faster
- Low RAM usage and GPU compatible for parallel processing and even faster inference

**Comment by Aryan-Chharia** [comment]
@DarshAgrawal14 Kindly include two pages along with project. A readme file explaining what the project is all about. And a methodology page explain the process in detail.
