### ISSUE TITLE
DOCUMENTAION AND ADDING NEW FEILDS.

### ISSUE THREAD

**Issue by Swytah** [Aryan-Chharia/Computer-Vision-Projects#16]
HI @Aryan-Chharia . I AM SWETA THIRD YEAR STUDENT.
We can add mode documentation for future reference and create an analysis of the accuracy using Python, and we can add one more field of generating text or the QR code.  I hope you liked my idea, and I am ready to work with you on this project.

**Comment by Aryan-Chharia** [comment]
Can you explain in more detail about this idea?
