### ISSUE TITLE
Face recognition system using opencv 

### ISSUE THREAD

**Issue by 09viv** [Aryan-Chharia/Computer-Vision-Projects#163]
Hi @Aryan-Chharia 

Description:
This project implements a face recognition system that utilizes OpenCV and the face_recognition library to detect and recognize faces in real-time from a webcam feed. It compares detected faces with a dataset of known faces, identifies them, and displays their names on the video stream.

Key Features:
Real-Time Face Detection: Detects faces in live video using OpenCV.
Face Recognition: Compares detected faces against known encodings to identify individuals.
Easy Dataset Management: Load known faces from a dedicated directory for easy updates.
Dynamic Display: Displays recognized names on the video feed with rectangles around faces.
Unknown Recognition Handling: Labels unrecognized faces as "Unknown."

Please assign me this issue under gssoc'24

**Comment by Aryan-Chharia** [comment]
This is very beginner level. Not required.
