### ISSUE TITLE
[FEAT] : Stone Paper Scissor Game using hand tracing with OpenCV

### ISSUE THREAD

**Issue by IkkiOcean** [Aryan-Chharia/Computer-Vision-Projects#165]
# Issue: Implement Stone Paper Scissor Game Using Hand tracing with OpenCV

### Description
We need to develop a Stone Paper Scissor game that uses real-time hand sign recognition through OpenCV. The game will allow players to interact using hand gestures for stone, paper, and scissors, providing a more engaging experience through computer vision.

### Requirements
- **Hand Gesture Recognition:**
- Use OpenCV to capture real-time video from the camera.
- Implement a model or algorithm to detect and classify hand signs for stone, paper, and scissors.
- Train or integrate an existing model for hand sign recognition if necessary.

- **Game Logic:**
  - Develop the game logic to compare the player's gesture with a randomly generated computer move.
  - Display the result of each round (win/lose/draw) in real time.
  - Implement a scoring system to keep track of the player's and computer's score.

- **User Interface:**
  - Use OpenCV to display the game in a window with real-time video feed and game results.
  - Provide clear instructions for the player to follow (e.g., how to position hands for each gesture).
  - Show the player's move, computer’s move, and the outcome (win/lose/draw) on the interface.

- **Performance:**
  - Ensure the hand gesture detection is accurate and responsive in real time.
  - Handle cases where the gesture is unclear or not recognized (e.g., display an error or prompt the user to try again).

### Expected Outcome
- A fully functional Stone Paper Scissor game where players can use hand gestures recognized via OpenCV to play against the computer.
- A user-friendly interface that displays the player’s hand gestures, computer moves, and game results in real time.

**Comment by Aryan-Chharia** [comment]
Go Ahead!

**Comment by IkkiOcean** [comment]
@Aryan-Chharia please assign level 2 atleast, I will have to design the UI also for this.

**Comment by Aryan-Chharia** [comment]
Project additions are Level 1 only

**Comment by Megha-Malviya** [comment]
https://github.com/Vaibhav22p-qw
can you assign me this issue . i would like to work on it.
