### ISSUE TITLE
Sign Language to Speech Using Computer Vision and Keras

### ISSUE THREAD

**Issue by rithvikreddybasani** [Aryan-Chharia/Computer-Vision-Projects#166]
I developed a sign language to speech conversion system using Keras and computer vision. The system employs a convolutional neural network (CNN) to accurately interpret sign language gestures and convert them into spoken words. For speech synthesis, I integrated pyttsx3 and gTTS, enabling seamless communication.

https://camo.githubusercontent.com/33d3a485382e218022a1f7e30125afa713a58d63321924ebfe85cdeb874f7b53/68747470733a2f2f7265732e636c6f7564696e6172792e636f6d2f64657171686c76356e2f696d6167652f75706c6f61642f76313731393436303039332f78666c646b676d6f7668686e63676166766772652e706e67

Can you pls assign me this @Aryan-Chharia?

**Comment by Aryan-Chharia** [comment]
Your issue is same as #22. Comment on that issue. I will assign that one. Meanwhile I will close this one.
