### ISSUE TITLE
Pokémon Data Analysis & Legendary Classification 

### ISSUE THREAD

**Issue by thejatingupta7** [Aryan-Chharia/Computer-Vision-Projects#168]
The project uses the open Pokémon dataset for advanced data analysis & legendary prediction of the Pokémon. It Uses advanced data analysis techniques and Various machine learning models, including neural networks, reaching an accuracy of 99%
![image](https://github.com/user-attachments/assets/c1e6de73-cb9b-47d4-aff4-301d5a18cd7d)

**Comment by Aryan-Chharia** [comment]
Not Required
