### ISSUE TITLE
Helmet Detection Using CNN and Open CV

### ISSUE THREAD

**Issue by eeshan15** [Aryan-Chharia/Computer-Vision-Projects#186]
@Aryan-Chharia I want to work on a Deep Learning Project called Helmet Detection using CNN and Opencv. It will classify people with wearing helmets or not using CNN and Opencv will help for image preprocessing,Object Detection and Bounding Box Drawing.Please assign this to me under the labels of GSSOC'24 and Hacktoberfest labels.Thankyou

**Comment by eeshan15** [comment]
Hi @Aryan-Chharia was stuck in mid sem exams now I will start working please respond to this comment so that i can confirm your activity status. Thank you and sorry as well

**Comment by Aryan-Chharia** [comment]
ok

**Comment by SimranShaikh20** [comment]
@Aryan-Chharia assign me this issue !
