### ISSUE TITLE
Real-time vehicle count and classification

### ISSUE THREAD

**Issue by Megha-Malviya** [Aryan-Chharia/Computer-Vision-Projects#190]
Create something that watches video to identify objects. and as counting the no. of vehicle in the parking area and enhance it by resetting the count after a certain time, improving detection accuracy, or implementing tracking for better counting.

https://github.com/Vaibhav22p-qw
can you assign me this issue so i can contribute and work on this issue.

**Comment by Aryan-Chharia** [comment]
#33 is similar to this issue.
