### ISSUE TITLE
Add Cat Dog Classifier Project

### ISSUE THREAD

**Issue by tanishqkolhatkar93** [Aryan-Chharia/Computer-Vision-Projects#191]
As part of freeCodeCamp's Machine Learning with Python curriculum, I had to work on the project "Cat And Dog Image Classifier" to create a model that classifies mixed images of cats and dogs as either cats or dogs. I used Image Data Generator to augment the images through flipping horizontally or vertically, zooming, and shifting vertically or horizontally and used Convolutional Neural Networks for classification.

This project made me comfortable working with deep learning and images and made me feel more motivated with image-based projects.  I am a GSSOC'24 Extended and Hacktoberfest Contributor.

**Comment by Aryan-Chharia** [comment]
this repo has many classification models / projects available. This one is redundant
