### ISSUE TITLE
Add Eye and Blink Detection

### ISSUE THREAD

**Issue by tanishqkolhatkar93** [Aryan-Chharia/Computer-Vision-Projects#203]
@Aryan-Chharia

I want to add a new Project Eye and Blink Detection

The project aims to develop a Eye and blink detection that takes an image of eye as input, recognizes the blinking of eyes, we can extract any facial structure from the 68 Facial Landmarks that we detected. So, we’ll extract the landmarks of the eyes i.e 6 (x,y) coordinates for each eye, for any given face in an image. And then we’ll calculate the EAR for these landmarks.
The image the overall value of EAR was constant throughout except at one point i.e when the eye is blinked, making it one of the most simple and most efficient ways of detecting an eye blink.

**Comment by Satyabrat2005** [comment]
@Aryan-Chharia  

I want to add a project in Eye and Blink Detection 

Project main theme :- Advanced Eye and Blink Detection with Emotion Recognition & Fatigue Monitoring where in this project,  aims to detect eye blinks, recognize emotional states through eye movements, and monitor fatigue based on blinking patterns and real-time feedback.  By incorporating emotion recognition, fatigue monitoring, and real-time feedback, it steps into areas with significant real-world impact, like driver safety or mental health monitoring.

Tech Stack used :- OpenCv , Mediapipe , Python , Machine Learning 

What will be inside project :- Emotion Recognition(From eye blinking and moving pattern recognize emotion state as stress or relaxation )

Fatigue Monitoring :- (Detect frequent blinking to indicate fatigue, provide real time feedback to prevent accidents ) 

Approach Of this project :- 
Data Collection ( Capture Eye movement and blinking pattern) 
Landmark Detection (Extract key landmarks from the eyes using a pre-trained facial landmark)
EAR Calculation (Measure the Eye Aspect Ratio (EAR), calculate average EAR for emotion and fatigue monitoring.
Fatigue Detection (Implement a fatigue monitoring system by detecting slow eye closures and increasing blink frequency)
Real-Time Feedback

**Comment by Aryan-Chharia** [comment]
@tanishqkolhatkar93 Thanks for the idea but there are multiple detection projects in the repo. I would like to focus on a different topic now. Thx for suggestion though.
