### ISSUE TITLE
 ADD BIRDS SPECIES CLASSIFICATION

### ISSUE THREAD

**Issue by Aditijainnn** [Aryan-Chharia/Computer-Vision-Projects#205]
BIRDS SPECIES CLASSIFICATION ADD THIS MODEL
ASSIGN THIS TO ME UNER GSSOC EXT

**Comment by Satyabrat2005** [comment]
@Aryan-Chharia please assign this work to me 

The Bird Species Classification project leverages deep learning and image processing to classify bird species from images. The primary tech stack includes Python for programming, with frameworks like  PyTorch for building and training convolutional neural networks (CNNs). Will add more tools inside project 

Please Assign this work to me

**Comment by sagar27sahu** [comment]
Hi , 
I’m interested in working on the bird species classification task. Could you please assign this task to me? 
Thank you!
