### ISSUE TITLE
Real TIme Crowd counting Uisng YOLO v3

### ISSUE THREAD

**Issue by Shekhar-Raj** [Aryan-Chharia/Computer-Vision-Projects#211]
<h2>Please assign me the issue so that i contribute the project Real TIme Crowd Counting using YOLOV3 and Computer Vision!</h2>

<h3>Demo</h3>

![image](https://github.com/user-attachments/assets/fd7bd1e1-4f4b-49d4-bf3e-7f60ba0d5e71)

**Comment by Aryan-Chharia** [comment]
@Shekhar-Raj Few questions -
1.) Will this work on video or just pictures
2.) Is there a demo available ?
