### ISSUE TITLE
Add Hardware and Software Requirements for transfer_learning.ipynb

### ISSUE THREAD

**Issue by praveenaneredimalli** [Aryan-Chharia/Computer-Vision-Projects#214]
Hey  @Aryan-Chharia , the README does not specify the hardware and software requirements needed to run the transfer_learning.ipynb notebook, which may cause confusion for users setting up their environment. Adding this information would greatly enhance usability.

**Comment by Aryan-Chharia** [comment]
@praveenaneredimalli can you specify in which location are you planning to add the requirements ?
