### ISSUE TITLE
Real-Time Object Counter Streamlit App - YOLOv8 + OpenCV

### ISSUE THREAD

**Issue by rakheshkrishna2005** [Aryan-Chharia/Computer-Vision-Projects#215]
### Since I was screen recording FPS dropped. It was around 30 FPS normally.
---
### Project Overview
I would like to contribute a **Real-time Object Tracker** project. It is a Streamlit dashboard that counts objects in real-time using **COCO dataset classes**, **YOLOv8**, and **OpenCV**.

### Demo Video:
https://github.com/user-attachments/assets/3408fee5-e82b-47bc-8282-eb84752b7d96

### Key Features:
- Real-time **Object detection** using YOLOv8 and OpenCV.
- **Supports video uploads (MP4, AVI, MOV, MPEG4)**, allowing users to easily process pre-recorded videos.
- Webcam integration for live video processing.
- CUDA GPU acceleration for faster processing.

### Project Structure:
- `app.py`, `main.css`, `requirements.txt`, `yolov8n.pt`, `README.md`
- Screenshots and output examples are available to illustrate the interface.

**Comment by Aryan-Chharia** [comment]
@rakheshkrishna2005 this project is already in the repo. thx for creating the issue.
