### ISSUE TITLE
Add 3D Object Reconstruction 

### ISSUE THREAD

**Issue by Satyabrat2005** [Aryan-Chharia/Computer-Vision-Projects#220]
@Aryan-Chharia i want to contribute in this project 

Main theme of this project :- 3D Object Reconstruction using Stereo Vision involves capturing two images of a scene from slightly different perspectives. By comparing these images, a disparity map is generated, which shows the difference in position between corresponding points in the two images. 

Using this disparity data, depth information is calculated, allowing the reconstruction of the 3D structure of the scene.

Here are some examples 

![left_image](https://github.com/user-attachments/assets/54a4fa2d-ddc9-4893-b7de-10c05b10fae2)
Here is Left image (of my room)

![right_image](https://github.com/user-attachments/assets/277a088d-2241-44e9-ad78-f759fab4b14a)
Here is Right image (of my room)

And here is the DISPARITY IMAGE
![Screenshot 2024-10-17 104329](https://github.com/user-attachments/assets/783178c5-c971-4d02-b26f-55716e407f4e)

**Comment by Aryan-Chharia** [comment]
@Satyabrat2005 try not to create dublicate issue. Check the another issue. I have assigned that one
