### ISSUE TITLE
Enable Mouse Control through Eye Tracking

### ISSUE THREAD

**Issue by IkkiOcean** [Aryan-Chharia/Computer-Vision-Projects#225]
#### Description
Implement a feature that allows users to control the mouse cursor using their eye movements. This functionality aims to enhance accessibility for users with mobility impairments and provide an innovative way to interact with the application.

#### Objectives
- Develop an eye-tracking system that accurately detects and interprets users' eye movements.
- Translate eye movements into mouse cursor movements, allowing users to navigate the interface seamlessly.
- Implement click functionality triggered by specific eye gestures (e.g., blinking, gaze hold).

**Comment by sagar27sahu** [comment]
Hi ,

I noticed that the feature request for eye-tracking mouse control is currently unassigned, and I believe I can contribute to its implementation. This feature would greatly enhance accessibility for users with mobility impairments, and I’d love to take it on and bring it to life.

I have experience in working with [mention any relevant technologies, e.g., eye-tracking software, computer vision, etc.], which I think would be valuable for this project. If you think it’s a good fit, could you please assign this task to me?

Looking forward to your response!

**Comment by Satyabrat2005** [comment]
i think this project will not workout because of selction and pupil detection 
as we can detect pupil but it will fails when we move our face and pupil to another direction 

+ Blinking ( for clicking function) will not workout because of normal blinking he can click other files or orther things too !!

**Comment by Satyabrat2005** [comment]
@Aryan-Chharia  should I open one issue with name of mouse tracking from hand gestures that will give great result than eye one !!

**Comment by IkkiOcean** [comment]
I opened this issue since I want to work on it. so assign it to me please

**Comment by Satyabrat2005** [comment]
> I opened this issue since I want to work on it. so assign it to me please

no worries sir you do . 
i just see the project in my pov and tell what changes can done

**Comment by Aryan-Chharia** [comment]
@IkkiOcean go ahead
