### ISSUE TITLE
I want to add "Gender Age Ethnicity Emotion Detector using DeepFace"

### ISSUE THREAD

**Issue by madhavi-peddireddy** [Aryan-Chharia/Computer-Vision-Projects#233]
Project Description:
This project implements a gender, age, ethnicity, and emotion detection system using DeepFace, MTCNN, OpenCV, and Streamlit. The app allows users to either capture a live photo through a webcam or upload an image containing faces. The MTCNN detector identifies faces within the image, and for each detected face, the system analyzes facial attributes such as gender, age, race, and emotion using DeepFace.

Once faces are detected, the image is processed to highlight the faces with bounding boxes, and detailed results (gender, age, race, and emotion) are displayed for each face in a structured format. This interactive application provides real-time results, making it suitable for applications in computer vision, user profiling, or entertainment settings. The use of Streamlit ensures an easy-to-use web interface with features like webcam capture, image upload, and face attribute visualization.
![Screenshot (125)](https://github.com/user-attachments/assets/3b1c3d78-6f25-49aa-9e47-591661eb8a5a)
![Screenshot (126)](https://github.com/user-attachments/assets/031acd20-66fe-4f4a-8456-7f3c0c21c826)
![Screenshot (127)](https://github.com/user-attachments/assets/2f506e16-54d7-4687-8d34-5110f4644cbd)
![Screenshot (128)](https://github.com/user-attachments/assets/302a60e4-9574-404b-bb78-da3c5808dd3d)

@Aryan-Chharia 

I want to work on this issue. Please assign me

**Comment by Aryan-Chharia** [comment]
#106
