### ISSUE TITLE
Add Sentiment Analysis of Restaurant Reviews project 

### ISSUE THREAD

**Issue by Tusharb331** [Aryan-Chharia/Computer-Vision-Projects#234]
## Overview

This project focuses on sentiment analysis using machine learning techniques. The goal is to classify the sentiment of textual data into positive, negative, or neutral categories. By leveraging various machine learning algorithms, this project aims to provide insights into customer opinions expressed in restaurant reviews.

## Technologies Used

- **Python**
- **NLTK (Natural Language Toolkit)**
- **Scikit-learn**
- **Jupyter Notebook**

**Comment by Aryan-Chharia** [comment]
thanks for suggestion. I dont think this project belong to computer vision repo.
