### ISSUE TITLE
Creating a Gesture based Virtual keyboard 

### ISSUE THREAD

**Issue by Panchadip-128** [Aryan-Chharia/Computer-Vision-Projects#237]
The Gesture-Based Virtual Keyboard is an innovative project that enables users to type using hand gestures detected through a webcam. By integrating hand tracking with a virtual keyboard interface, this application allows for a seamless typing experience without the need for physical input devices.

**Comment by Panchadip-128** [comment]
@Aryan-Chharia Please review once and if possible do assign under suitable labels , Thanks

**Comment by Aryan-Chharia** [comment]
thanks for suggestion. the hand gesture recognition is already there in repo and issue are already assigned.
