### ISSUE TITLE
Request for File Upload for GSSOC 2024 Pull Request

### ISSUE THREAD

**Issue by a-n-u-vanguri** [Aryan-Chharia/Computer-Vision-Projects#239]
Hello @Aryan-Chharia ,

I hope this message finds you well!

As part of my GSSOC Ext 2024 project on image detection, I want to make a pull request that includes the necessary code. To ensure everything works smoothly, could you please upload the relevant image file(s) needed for testing?

Your assistance would be greatly appreciated, and it will help us enhance the functionality further.

Thank you so much for your support!
![image](https://github.com/user-attachments/assets/238c83df-0857-4de8-b148-bc753f8e9751)

**Comment by Aryan-Chharia** [comment]
there are similar project already in the repo. thanks for suggestion.
