### ISSUE TITLE
Add requirements file

### ISSUE THREAD

**Issue by theomkardeshpande** [Aryan-Chharia/Computer-Vision-Projects#24]
Add requirements file including modules used in project to install easily

Assign me for Gssoc 24 ext

**Comment by alo7lika** [comment]
To create a requirements.txt file for your Plant Health Monitoring System project on GitHub, you need to list all the Python libraries and dependencies your project requires. This file allows users to easily install the necessary packages to run your project. Here's how to do it:

1. Identify Dependencies: Determine the libraries your project relies on. Common libraries for a Plant Health Monitoring System might include:

- numpy for numerical computations
- pandas for data manipulation
- opencv-python for image processing
- tensorflow or keras for building machine learning models
- flask for creating a web application (if applicable)
- matplotlib for data visualization

2. Create the File: Open a text editor or IDE and create a new file named requirements.txt.

3.List Packages: In the requirements.txt file, list each package on a new line, optionally specifying the version if necessary. For example:

- numpy
- pandas
- opencv-python
- tensorflow
- flask
- matplotlib

4. Upload to GitHub: Once you have finalized the file, save it and add it to your project directory. Then, commit and push the changes to your GitHub repository.

This requirements.txt file will facilitate the setup process for other users or collaborators, enabling them to replicate your environment by simply running pip install -r requirements.txt in their terminal.

assign me this work @Aryan-Chharia .i would love to contribute

**Comment by alo7lika** [comment]
To add a requirements file to your GitHub repository, follow these steps:

1. Create a Requirements File: Open your text editor and create a new file named requirements.txt. This file will list all the dependencies your project needs, one per line. For example:

- pandas
- numpy
- scikit-learn

2. Add the File to Your Repository: Save the requirements.txt file in the root directory of your project.

3.Commit Your Changes: Open your terminal or command prompt, navigate to your project directory, and run the following commands:

- git add requirements.txt
- git commit -m "Add requirements file"

4.Push to GitHub: Finally, push your changes to your GitHub repository using:

- git push origin main
- (Replace main with your branch name if it’s different.)
- 

Now, your GitHub repository will have a requirements.txt file, making it easier for others to install the necessary packages for your project.

assign me this work @aryan-chharia, I would love to contribute

**Comment by Aryan-Chharia** [comment]
Go Ahead!

**Comment by Bhavya445** [comment]
can u plss assign this to me

**Comment by theomkardeshpande** [comment]
I have added the file please review it
