### ISSUE TITLE
Proposal to Add Cricket Bat, Ball, and Pitch Detection Using Computer Vision

### ISSUE THREAD

**Issue by cosmicishan** [Aryan-Chharia/Computer-Vision-Projects#242]
Hi, @Aryan-Chharia 

I  would like to contribute by adding a feature for detecting cricket bats, balls, and the pitch area using computer vision techniques. The goal is to build a robust detection model that can accurately identify and track these key elements in both images and video footage of cricket matches.

Please assign this task to me.

**Comment by cosmicishan** [comment]
> Hi, @Aryan-Chharia I would like to contribute to this project by developing a feature for detecting cricket bats, balls, and the pitch area using computer vision techniques. I aim to create a robust detection model capable of accurately identifying and tracking these elements in both images and video footage of cricket matches. Please assign this task to me.

Wanna work on it Together?

**Comment by Aryanshh** [comment]
Sure Definitely, how can we discuss about the what we have to work upon

**Comment by cosmicishan** [comment]
@Aryanshh Contact me on WhatsApp: +919998084322

Let's discuss further.
