### ISSUE TITLE
Add image-to-text model

### ISSUE THREAD

**Issue by BhavyaFattania** [Aryan-Chharia/Computer-Vision-Projects#25]
Image-to-text Image captioning model generates conditional and unconditional captions based on image uploaded by user
Image captioning is the task of describing the content of the image using textual representation. It has been used in many applications such as semantic tagging, image retrieval, early childhood learning, human-like robot–robot interactions, visual question answering tasks, and medical diagnosis.
this is a simple working demo of how this model works
![Screenshot 2024-10-02 023131](https://github.com/user-attachments/assets/74248553-12e4-4179-b4ae-d3421c6a8d04)

**Comment by alo7lika** [comment]
Image-to-text models are powerful tools that extract meaningful information or generate descriptive text from visual inputs. These models are commonly used in applications such as document digitization, accessibility features, and content creation. One widely-used category is Optical Character Recognition (OCR), which translates text from scanned images, PDFs, or photographs into editable formats. Tools like Tesseract OCR (open-source, developed by Google) and Microsoft OCR are popular for their accuracy and ease of integration. In more complex scenarios, image captioning models come into play, generating natural language descriptions of images. Early models like Show, Attend and Tell use attention mechanisms to focus on important parts of an image, while advanced models, like transformer-based architectures (e.g., GPT-4), provide more nuanced and context-aware descriptions. Vision-language models, such as CLIP (Contrastive Language-Image Pretraining by OpenAI) and BLIP (Bootstrapped Language-Image Pretraining), combine visual and textual information for tasks like visual question answering, offering a more comprehensive approach to interpreting and describing images. These models have diverse applications, from enhancing accessibility for visually impaired individuals to enabling automated content generation and data extraction.

assign me this work and add labels gssoc and hacktoberfest

**Comment by BhavyaFattania** [comment]
copying content from chatgpt and making a working model is far more different

> Image-to-text models are powerful tools that extract meaningful information or generate descriptive text from visual inputs. These models are commonly used in applications such as document digitization, accessibility features, and content creation. One widely-used category is Optical Character Recognition (OCR), which translates text from scanned images, PDFs, or photographs into editable formats. Tools like Tesseract OCR (open-source, developed by Google) and Microsoft OCR are popular for their accuracy and ease of integration. In more complex scenarios, image captioning models come into play, generating natural language descriptions of images. Early models like Show, Attend and Tell use attention mechanisms to focus on important parts of an image, while advanced models, like transformer-based architectures (e.g., GPT-4), provide more nuanced and context-aware descriptions. Vision-language models, such as CLIP (Contrastive Language-Image Pretraining by OpenAI) and BLIP (Bootstrapped Language-Image Pretraining), combine visual and textual information for tasks like visual question answering, offering a more comprehensive approach to interpreting and describing images. These models have diverse applications, from enhancing accessibility for visually impaired individuals to enabling automated content generation and data extraction.
> 
> assign me this work and add labels gssoc and hacktoberfest

**Comment by Aryan-Chharia** [comment]
@BhavyaFattania Go Ahead!
