### ISSUE TITLE
Virtual Mouse controlled by hand gestures using OpenCV and MediaPipe

### ISSUE THREAD

**Issue by Shantnu-singh** [Aryan-Chharia/Computer-Vision-Projects#250]
## Proposed Features:

- **Hand Detection & Tracking:** Uses MediaPipe for detecting hand landmarks and tracking hand movements in real-time.
- **Cursor Control:** Map hand movements to control the mouse cursor's position on the screen.
- **Gesture-Based Actions:** Implement gestures such as pinching for clicks, hand movement for scrolling, and more.
- **Smooth and Adaptive Motion:** Ensure smooth cursor movement using filtering techniques to avoid jittery behavior.

**Comment by Soumili-Saha** [comment]
I would like to work on this.

**Comment by waifuexists** [comment]
I would like to work on this issue I had performed similar project if want I can share github link will be great to help for better insight oand learning of project

**Comment by gaurimakhija** [comment]
i would also like to contribute in this virtual gesture detection using open cv..
