### ISSUE TITLE
Adding sentiment classifier to the image to text model 

### ISSUE THREAD

**Issue by gaurimakhija** [Aryan-Chharia/Computer-Vision-Projects#251]
@Aryan-Chharia  By adding  sentiment classifier we can  analyse the  image emotion and gives unconditional captions . for example  "A joyful dog is running happily across the sunlit sand." instead of the dog is running across the sand .

for this i would like to use CNN which consists of 3 layers that extracts features very well and provides us with an accuracy  in sentiment  anaylsis. 
please assign this to me .

**Comment by Aryan-Chharia** [comment]
already in repo
