### ISSUE TITLE
Add Realtime human count detection project 

### ISSUE THREAD

**Issue by Tusharb331** [Aryan-Chharia/Computer-Vision-Projects#253]
### Description:
I would like to suggest adding the Real-Time Human Detection and Counting project to this repository. This project is designed to detect and count humans in real-time using machine learning models and computer vision techniques. It could greatly enhance the capabilities of this repo by offering an additional module for human detection and counting.

### Key Features:
- **Real-Time Human Detection**: Uses state-of-the-art deep learning models for detecting humans in video streams or images.
- **Accurate Counting**: Efficiently counts the number of people in a given frame, making it suitable for use cases like monitoring, crowd control, or attendance systems.
- **Technology Stack**: Python, OpenCV, TensorFlow/Keras, and other relevant libraries.
- **Open Source**: The project is open-source, making it easy to integrate and modify according to your repository's needs.

### Benefits:
- It would add a robust feature for real-time detection and analysis.
- Can be a great addition for those looking for practical implementations of human detection using AI/ML.
- Helps expand the functionality of this repository, attracting a broader audience.

### Screenshots:

![13](https://github.com/user-attachments/assets/4748a30b-0103-45ba-a146-031f2afd6676)
![14](https://github.com/user-attachments/assets/4193e90f-6d80-4ee5-b170-0566c7f5f6e6)

**Comment by Tusharb331** [comment]
Please assign this project. It's a good to go project for computer vision.

**Comment by Abhiiesante** [comment]
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted.
I have some experience in opencv
