### ISSUE TITLE
ADD RATIOS IN THE DISPARITY MAP FOR MNORE PRECISE CONSTRUCTIONS

### ISSUE THREAD

**Issue by aryash45** [Aryan-Chharia/Computer-Vision-Projects#257]

**Comment by Abhiiesante** [comment]
we can address this using normalization or refining. 
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted

**Comment by aryash45** [comment]
how can issue this please tell me i am just a beginner

**Comment by Abhiiesante** [comment]
You can compute ratios of disparity based on the focal length and baseline (distance between the two cameras). 
or
after calculating the initial disparity at the pixel level, interpolation techniques (such as bilinear interpolation) can be applied to estimate disparity at subpixel precision.

**Comment by aryash45** [comment]
OH RIGHT THANKS

**Comment by aryash45** [comment]
hey @Aryan-Chharia can you please assign this issue to @Abhiiesante as i am not able to do it

**Comment by aryash45** [comment]
thank you so much
