### ISSUE TITLE
Automatic Number Plate Recognition using image processing

### ISSUE THREAD

**Issue by riyarane46** [Aryan-Chharia/Computer-Vision-Projects#26]
@Aryan-Chharia 

i will develop Automatic Number Plate Recognition (ANPR) is an image processing technology used to identify and extract vehicle license plate numbers from images or video frames. This project involves capturing images of vehicles, pre-processing the images , detecting the license plate region . 

please assign me this issue under gssoc24 extd and hacktoberfest.

**Comment by Aryan-Chharia** [comment]
Go Ahead!
