### ISSUE TITLE
Creating a Multimodal Visual Question & Answer (VQA) model 

### ISSUE THREAD

**Issue by Panchadip-128** [Aryan-Chharia/Computer-Vision-Projects#265]
This project focuses on developing Visual Question Answering (VQA) systems using two models: CLIP (Contrastive Language-Image Pretraining) and BLIP (Bootstrapped Language-Image Pretraining). The goal of VQA is to answer questions about an image by jointly learning from both textual and visual information. This project demonstrates how to utilize the CLIP and BLIP models for VQA tasks, and it includes the training, validation, and testing procedures, as well as metrics for evaluation.

**Comment by Abhiiesante** [comment]
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted

**Comment by Panchadip-128** [comment]
@Abhiiesante Hi, i authored the thread first so it should be assigned to me first

Please create a new thread with similar or different problem if you want

**Comment by Panchadip-128** [comment]
Can you please re-label this PR as level2 or level3( suitable) , since it contains extensive frameworks and does make use of both BLIP and CLIP advanced models,and implements them seperately with two notebook files and also concludes with a comparison between the two with appropriate ML metrics, Do review once and please re-label with appropriate level Thanks. I created a PR with #278 for this issue

**Comment by Aryan-Chharia** [comment]
@Panchadip-128 project additions are level 1 only
