### ISSUE TITLE
Add Self Driving Car Project

### ISSUE THREAD

**Issue by tanishqkolhatkar93** [Aryan-Chharia/Computer-Vision-Projects#266]
@Aryan-Chharia I want to work on a Deep Learning Project called Self driving car using Opencv. It will detect the lanes of the highway to avoid the collapsing of cars with each other .In this we used canny edge detection algorithm.
Please assign this to me under the labels of GSSOC'24 and Hacktoberfest labels.Thankyou

**Comment by Abhiiesante** [comment]
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted
