### ISSUE TITLE
Real Time Text Extraction

### ISSUE THREAD

**Issue by ramana2074** [Aryan-Chharia/Computer-Vision-Projects#271]
real-time captured image using a web cam or any other camera and extract the text from that image by removing noise from it. I use `OpenCV` for capturing the real-time image and `pytesseract` for text extraction from the captured image.

**Comment by Pratik9113** [comment]
Can u assign this to me
1.  Text cleaning Remove unwanted words :- tokenization, stemming, stopwords and Vectorization.
2. Then Open CV for capturing real-time image 
3. Necessary libraries for extracting text 
4. You can even use Microsoft azure services which is more efficient in terms of extracting text .
