### ISSUE TITLE
AI-Powered Wildlife Monitoring System

### ISSUE THREAD

**Issue by shriyadindi** [Aryan-Chharia/Computer-Vision-Projects#274]
Description: Create a system that can automatically detect and classify wildlife using cameras placed in natural environments. It can be extended for endangered species monitoring.

Tech stack: OpenCV, TensorFlow, YOLO, or ResNet for classification, possibly with pre-trained models.

**Comment by Aryan-Chharia** [comment]
#149 is this similar to this

**Comment by shriyadindi** [comment]
@Aryan-Chharia no, thats classifaction and this monitoring system

**Comment by Aryan-Chharia** [comment]
>Description: Create a system that can automatically detect and classify wildlife using cameras placed in natural environments

What is the difference between this project and the one already in the repo?

>It can be extended for endangered species monitoring.

What system are proposing to add the monitoring feature? Also can you show the results (video or pic) here in the issue so as to understand your project better.
