### ISSUE TITLE
Real-Time Sign Language Recognition

### ISSUE THREAD

**Issue by shriyadindi** [Aryan-Chharia/Computer-Vision-Projects#275]
Description: This project focuses on building a system that uses computer vision to recognize sign language gestures in real-time, translating them into text or speech. The system will track hand gestures using MediaPipe Hands and leverage temporal relationships between movements with LSTM or 3D CNNs.
Tech stack: TensorFlow, Keras, OpenCV, MediaPipe Hands for tracking hand gestures.

**Comment by Aryan-Chharia** [comment]
already in the repo
