### ISSUE TITLE
Body Measurements Using Computer Vision 

### ISSUE THREAD

**Issue by call-meRavi-SHORT-CODE** [Aryan-Chharia/Computer-Vision-Projects#276]
Key Features:

1) Automated Body Detection: 
                 Detect and mark key body points (e.g., shoulders, hips) for accurate measurements.

2) Specific Body Measurements:
                Capture circumferences (chest, waist, hips) and lengths (arm, leg) for size estimation.

3) Multi-angle Support: 
                Enable measurements from different image angles for improved accuracy.

**Comment by Aryan-Chharia** [comment]
#5 is this same as this?

**Comment by call-meRavi-SHORT-CODE** [comment]
yes

**Comment by call-meRavi-SHORT-CODE** [comment]
utilizing mediapipe and OpenCV to measure the real-time body measurements.

**Comment by Aryan-Chharia** [comment]
since this is the same issue I am closing this one
