### ISSUE TITLE
Add Logo Detection in Images

### ISSUE THREAD

**Issue by Aditijainnn** [Aryan-Chharia/Computer-Vision-Projects#277]
In this project, the goal is to build a machine learning model that can detect and classify logos in images. This task can be applied in real-world applications like detecting brand logos in social media images, videos, or advertisements to track brand visibility or copyright violations.

assign this to me under gssoc ext and hacktoberfest

**Comment by Aryan-Chharia** [comment]
classficiation is already in the repo
