### ISSUE TITLE
Document intelligence 

### ISSUE THREAD

**Issue by Balamuralikrishna123** [Aryan-Chharia/Computer-Vision-Projects#279]
Document processing is a common task in many business scenarios. Organizations can use this tool Document Intelligence to automate data extraction across document types, such as receipts, invoices, and more.processing multiple documents in votes and any registrations through papers need much time we can save the time by using this tool.

**Comment by Aryan-Chharia** [comment]
is this same as OCR?

**Comment by Balamuralikrishna123** [comment]
Yes it is.

**Comment by Balamuralikrishna123** [comment]
A scenario where we need to collect huge amount of data from the real
paper documents with some pattens and without patterns example in elections
or in any registrations where data collected on papers . to make those work
simpler we can use models to train the patterns  .

**Comment by Aryan-Chharia** [comment]
#14 is your project same as this then?

**Comment by Balamuralikrishna123** [comment]
I don’t get his project  but probably may be same for some extent but mine was to extract the huge data if the pattern is simpler we can use pre built models, if not we can train the model  to get the pattern and extraxt the data  by document analysis.

**Comment by Aryan-Chharia** [comment]
I check it. It is same to an extent so I am closing this issue
