### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by Ayush07571** [Aryan-Chharia/Computer-Vision-Projects#28]
Hey @Aryan-Chharia, I think so that your repository needs a code of conduct. I would be happy to contribute in it. Can you please add labels and assign me this issue to work on.

**Comment by alo7lika** [comment]
**Overview of the Code of Conduct**
The Code of Conduct establishes clear expectations for behavior within our community. It aims to create an inclusive, respectful, and harassment-free environment for all participants, regardless of their background or identity.

**Key components of the Code include:**

1. Pledge: A commitment from all members to foster a welcoming atmosphere.
2. Standards: Examples of acceptable and unacceptable behavior to guide interactions.
3. Enforcement Responsibilities: Guidelines for community leaders on addressing misconduct.
4. Consequences: Clear repercussions for engaging in unacceptable behavior.
5. Reporting: A straightforward process for reporting issues or concerns.
6. By adhering to this Code, we ensure a positive and productive experience for everyone involved in the project.

ASSIGN ME THIS WORK @Aryan-Chharia. I WOULD LOVE TO CONTRIBUTE

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
and add the gssoc-ext label
