### ISSUE TITLE
Handwritten text recognition model using OpenCV

### ISSUE THREAD

**Issue by Sameeratweb** [Aryan-Chharia/Computer-Vision-Projects#281]
A Handwritten Text Recognition model using OpenCV typically involves processing scanned or camera-captured images of handwritten text. OpenCV is utilized for image preprocessing tasks such as noise removal, and contour detection to isolate individual characters or words. 

please allow me with this issue with relevant tags under gssoc

**Comment by Aryan-Chharia** [comment]
already in the repo
