### ISSUE TITLE
Add New Project Real-Time 3D Pose Estimation Project with Unity Integration

### ISSUE THREAD

**Issue by karthikyandrapu** [Aryan-Chharia/Computer-Vision-Projects#287]
### Description:
I would like to contribute a **Real-Time 3D Pose Estimation** project to this repository as part of **GSSoC-ext** and **Hacktoberfest**. This project captures real-time 3D pose data using Mediapipe and OpenCV, then transmits the landmark positions to Unity via UDP for real-time interaction.

### Project Overview:
The project leverages a webcam feed to perform 3D pose estimation and transmits the 3D landmark data to Unity for visualization or game interactions. Key features include:
- Capturing 3D pose landmarks in real-time using Mediapipe
- Converting pose landmarks into JSON format
- Sending data via UDP to Unity for further processing and visualization
- Overlaying landmark positions on the video feed for visual feedback

### Implementation Highlights:
- **Grayscale and RGB Conversion:** Prepares video frames for Mediapipe processing
- **Mediapipe Pose Model:** Detects 3D pose landmarks using Mediapipe's built-in pose estimation model
- **3D Landmark Extraction:** Extracts 3D positions of landmarks in real-time
- **UDP Data Transfer:** Transmits data to Unity over a UDP socket for real-time syncing

### Example Output:
Example output shows 3D landmark visualization on Unity or a screenshot of the pose overlay in the OpenCV frame.  
*(Screenshot placeholder if available)*

📸 **Screenshots**: 
![Screenshot (232)](https://github.com/user-attachments/assets/c8e84503-4c05-411a-b331-53a373a9dfe7)

**Comment by Aryan-Chharia** [comment]
already in repo
