### ISSUE TITLE
Fisheye vs. Normal Calibration

### ISSUE THREAD

**Issue by Asmi-va** [Aryan-Chharia/Computer-Vision-Projects#29]
You are using different calibration methods for fisheye and non-fisheye cameras, but you haven't accounted for distortion coefficients in the non-fisheye case. In the non-fisheye branch, cv2.calibrateCamera returns more than just K and D; you'll also need to capture the distortion coefficients (D)
assign me this project so that i could fix the issue

**Comment by Aryan-Chharia** [comment]
Go Ahead

**Comment by Asmi-va** [comment]
I have corrected the code and have uploaded the resolved code file in the
fork repository
Hope so appeared in yours too !

**Comment by Aryan-Chharia** [comment]
@Asmi-va you have to make a pull request. Only then I can see the changes

**Comment by Asmi-va** [comment]
Hi aryan-Chharia I have made the pull up request please proceed with the
next steps
