### ISSUE TITLE
Lung Image Binary Classification (NEW ISSUE)

### ISSUE THREAD

**Issue by Pratzybha** [Aryan-Chharia/Computer-Vision-Projects#291]
Project Title -> Lung Image Binary Classification (Normal VS COVID Lung)
Dataset -> https://www.kaggle.com/datasets/tawsifurrahman/covid19-radiography-database/data

I would like to work on the above mentioned topic.

For -> GSSOC '24 EXT

**Comment by Aryan-Chharia** [comment]
already in the repo lung classification
