### ISSUE TITLE
I Want to add Bug Report, Enhancement Request, Documentation Update template

### ISSUE THREAD

**Issue by souvikpramanikgit** [Aryan-Chharia/Computer-Vision-Projects#296]
I want to add ->

- Bug Report
![image](https://github.com/user-attachments/assets/14b7f3c3-aea2-44f4-a05a-58d80042a6d4)

- Enhancement Request
![image](https://github.com/user-attachments/assets/299e1e25-ae6e-4142-8eef-05e317fc1c37)

- Documentation Update
![image](https://github.com/user-attachments/assets/9e1f1b8c-9e80-4252-8a58-591250f65799)

**Comment by souvikpramanikgit** [comment]
can i get level 2

**Comment by Aryan-Chharia** [comment]
no

**Comment by souvikpramanikgit** [comment]
@Aryan-Chharia merge this

**Comment by souvikpramanikgit** [comment]
why you close it instead of merge @Aryan-Chharia
