### ISSUE TITLE
Real time parking space detection project using opencv

### ISSUE THREAD

**Issue by Nikhith221B** [Aryan-Chharia/Computer-Vision-Projects#30]
I would like to add a project in which we can check in an image or in a video how many parking slots are available in realtime with number of available spaces(count)
@Aryan-Chharia assign it to me.
please look into this @Vaibhav22p-qw @c0sm0void

**Comment by mjgandhi2305** [comment]
I would like to addParking space counter which can detect the empty parking slots real time using opencv-python. @Aryan-Chharia kindly assign it to me

**Comment by Nikhith221B** [comment]
> I would like to addParking space counter which can detect the empty parking slots real time using opencv-python. @Aryan-Chharia kindly assign it to me

Hello @mjgandhi2305 the project i proposed contains the parking space counter ,kindly look into the issues which requires help or come with a new issue/enhancement

**Comment by Meetpidev** [comment]
@Aryan-Chharia 
### I want to work on it.. requested to assign me..
