### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by vamzx** [Aryan-Chharia/Computer-Vision-Projects#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Since this is a repository built for beginners as well, following a deeper dive into understanding models and getting familiar with the structure of each project will help.

### Suggested Change

- Fix typos or improve clarity in README files or code comments.
- Add a detailed explanation of models (e.g., YOLO, U-Net) and how they work.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/souvikpramanikgit/Computer-Vision-Projects/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [ ] I'm a Hacktoberfest contributor
- [ ] I am willing to work on this issue (optional)

**Comment by Aryan-Chharia** [comment]
are you still working on this?

**Comment by vamzx** [comment]
> are you still working on this?

Yes, I will be finishing up soon!

**Comment by vamzx** [comment]
@Aryan-Chharia Please review the Pull Request
