### ISSUE TITLE
Lemon Quality Segmentation

### ISSUE THREAD

**Issue by Pratzybha** [Aryan-Chharia/Computer-Vision-Projects#306]
Topic: Lemon Quality Segmentation
Dataset: https://www.kaggle.com/datasets/yusufemir/lemon-quality-dataset
In this project, I will explore three different approaches for image segmentation using deep learning models: Simple_CNN, AlexNet, and VGG.

GSSOC'24 - EXT

**Comment by Pratzybha** [comment]
@Aryan-Chharia Please look into it

**Comment by Absk024** [comment]
i would like to contribute @Aryan-Chharia
