### ISSUE TITLE
🧑‍💻: object size detection

### ISSUE THREAD

**Issue by Sameeratweb** [Aryan-Chharia/Computer-Vision-Projects#307]
### Title

object size detection

### Enhancement Aim

object size detection model involves using computer vision techniques to estimate the physical dimensions of an object in an image.

### Changes

Adding features by incorporating a computer vision model.

### Screenshots 📷

N/A

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Sameer Desai

### Participant Role

GSSOC

**Comment by Aryan-Chharia** [comment]
will get back to you soon
