### ISSUE TITLE
🧑‍💻: Implement Statistics and Performance Metrics in solve_sudoku_puzzle

### ISSUE THREAD

**Issue by Anushka-Pote** [Aryan-Chharia/Computer-Vision-Projects#308]
### Title

Implement Statistics and Performance Metrics in solve_sudoku_puzzle

### Enhancement Aim

To enhance the solve_sudoku_puzzle function, we propose the implementation of statistics and performance metrics. This feature will collect and display metrics related to the time taken for critical operations such as image loading, cell extraction, and Sudoku solving. Providing these insights will help in assessing the function's efficiency and diagnosing potential bottlenecks.

### Changes

Time Tracking for Key Operations

Display Metrics

Optional Verbose Mode

### Screenshots 📷

NA

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Anushka Pote

### Participant Role

GSSOC, Hacktoberfest

**Comment by Aryan-Chharia** [comment]
will get back to you soon

**Comment by Aryan-Chharia** [comment]
thanks for the issue. Sudoku solving is already in repo
