### ISSUE TITLE
[Doc]: Add the security

### ISSUE THREAD

**Issue by Dipanita45** [Aryan-Chharia/Computer-Vision-Projects#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Security

### Suggested Change

Security of the website

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/souvikpramanikgit/Computer-Vision-Projects/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I am willing to work on this issue (optional)

**Comment by Dipanita45** [comment]
Please assign me the issue 
@Aryan-Chharia

**Comment by Aryan-Chharia** [comment]
can you explain what is this all about?

**Comment by Dipanita45** [comment]
Add a security file in .md extension

**Comment by Aryan-Chharia** [comment]
attach some attachment like pic or text something for me to see what your gonna add

**Comment by Dipanita45** [comment]
Please assign me

**Comment by Dipanita45** [comment]
Please please assign me

**Comment by Aryan-Chharia** [comment]
no need of this issue thanks for suggestion

**Comment by Dipanita45** [comment]
Please assign me the issue

**Comment by Dipanita45** [comment]
Okay thank you
