### ISSUE TITLE
Door status checker using yolo model

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [Aryan-Chharia/Computer-Vision-Projects#312]
### Title

implement door status checker using yolo model

### Enhancement Aim

This system is a home monitoring model that detects whether a door is open or closed

### Changes

will use object detection and ocr

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Sanika Rahul Bhalerao

### Participant Role

gssoc-extd | contributor

**Comment by Aryan-Chharia** [comment]
already / similar in repo
