### ISSUE TITLE
🧑‍💻: object detection 

### ISSUE THREAD

**Issue by dino65-dev** [Aryan-Chharia/Computer-Vision-Projects#322]
### Title

Add Yolov5 model.

### Enhancement Aim

Upgrading your object detection implementation from YOLOv3 to YOLOv5 can bring several benefits, including improved accuracy, speed, and ease of use.

### Changes

I will add Yolov5  with implementation and code.

### Screenshots 📷

N/A

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Dinmay Kumar Brahma

### Participant Role

-  GSSOC-EXT 24
-  CONTRIBUTOR

**Comment by Aryan-Chharia** [comment]
pretty trivial
