### ISSUE TITLE
🧑‍💻: Adding  a  Grammar AutoCorrector model 

### ISSUE THREAD

**Issue by Peart-Guy** [Aryan-Chharia/Computer-Vision-Projects#323]
### Title

This is a model for Auto correcting Grammar in a text Input

### Enhancement Aim

A grammar autocorrector tool helps users write clearly and professionally by correcting errors instantly. It saves time, boosts confidence, and aids learning by showing suggested improvements.

### Changes

I want to add a  Grammar AutoCorrector model 

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Ankan

### Participant Role

GSSOC-24 EXTD

**Comment by Aryan-Chharia** [comment]
not revelent in this repo
