### ISSUE TITLE
🧑‍💻: CLIP Image Classification

### ISSUE THREAD

**Issue by dino65-dev** [Aryan-Chharia/Computer-Vision-Projects#324]
### Title

Enhanced Image Understanding with CLIP

### Enhancement Aim

Integrate CLIP into the Computer Vision project to enable sophisticated image-text understanding, enhancing visual recognition and classification tasks through advanced language-vision models.

## Features

- **Asynchronous Image Processing**: Utilizes Python's `asyncio` to load and classify images concurrently, improving performance when handling large batches.
  
- **Dynamic Prompt Generation**: Automatically generates classification prompts based on user-defined base terms, allowing for flexible and contextual image queries.

- **Confidence Thresholding**: Filters classification results based on a user-defined confidence threshold, enhancing accuracy by omitting less certain predictions.

- **Multi-Modal Retrieval**: Enables users to retrieve images based on textual descriptions and vice versa, offering a versatile tool for various multi-modal tasks.

- **Robust Error Handling**: Includes comprehensive error handling and logging to help diagnose issues related to image loading and processing.

- **Batch Processing**: Supports processing multiple images from a specified folder, making it suitable for large datasets.

- **GPU Acceleration**: Automatically utilizes GPU for faster model inference if available, significantly improving processing times.

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Dinmay Kumar Brahma

### Participant Role

- GSSOC-EXT 24
- CONTRIBUTOR

**Comment by Absk024** [comment]
i would like to contribute @Aryan-Chharia
