### ISSUE TITLE
🧑‍💻: Text Summarizing NLP Model

### ISSUE THREAD

**Issue by Peart-Guy** [Aryan-Chharia/Computer-Vision-Projects#325]
### Title

It will be a text summarization NLP model where user and type their huge paragraphs and the model will summarize it

### Enhancement Aim

People do face issues to summarize huge texts or students do face issues to learn huge texts. this model will help users to summarize those texts and use it according to their need, for example a learner can easily learn faster and understand the summarized text instead of going through huge paragraphs

### Changes

I want to add a Text Summarizing NLP Model

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Ankan

### Participant Role

GSSOC-24 EXTD

**Comment by Aryan-Chharia** [comment]
not relevent in this repo
