### ISSUE TITLE
Car Counter Project

### ISSUE THREAD

**Issue by Rohit131313** [Aryan-Chharia/Computer-Vision-Projects#33]
Hello @Aryan-Chharia ,

I would like to contribute a project called Car Counter. This project uses computer vision to count the number of vehicles passing through a particular signal in a video feed. It can be helpful for analyzing traffic flow and collecting data on vehicle movements in real-time.

Please assign me this issue, and I’ll be happy to start working on it.

**Comment by Reql75** [comment]
Hello @Aryan-Chharia  
I would like to contribute to this project
