### ISSUE TITLE
🧑‍💻: Gesture-Based Keyboard Interface Using Webcam

### ISSUE THREAD

**Issue by Niraj1608** [Aryan-Chharia/Computer-Vision-Projects#332]
### Title

Gesture-Based Keyboard Interface Using Webcam

### Enhancement Aim

build an innovative gesture-based keyboard interface using a webcam, allowing users to type interactively using hand gestures and eye tracking. The goal is to create a virtual keyboard where users can interact by using hand gestures for typing and eye movements for cursor control or selecting keys.

### Changes

**Gesture Controls:**
   - Move your hand to hover over virtual keys
   - Pinch index finger and thumb to "press" keys
   - Make a fist to close the keyboard
   - Use the "BACK" button for backspace
   - Use the "CLOSE" button or make a fist to exit

### Hand Detection
- Uses CVZone's HandTrackingModule
- Detection confidence threshold: 0.8
- Supports tracking of up to 2 hands

### Keyboard Layout
- QWERTY layout with special characters
- Additional control buttons (Backspace, Space, Close)
- Enhanced visual feedback system

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Niraj Parmar

### Participant Role

GSSOC

**Comment by Niraj1608** [comment]
@Aryan-Chharia assign me this issue

**Comment by Aryan-Chharia** [comment]
already in repo

**Comment by Niraj1608** [comment]
@Aryan-Chharia i checked this was gesture based volume controller and this is keyboard 
i added screenshot it check pls
![Screenshot 2024-11-06 164905](https://github.com/user-attachments/assets/b2c4217e-1a4e-4517-a6c3-7dc03e85e299)

**Comment by Niraj1608** [comment]
@Aryan-Chharia thank you
