### ISSUE TITLE
Add back-to-top scroll up button in readme

### ISSUE THREAD

**Issue by T-Fathima** [Aryan-Chharia/Computer-Vision-Projects#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to add back-to-top scroll up at the end of the readme file for easier navigation in lengthy readme file.
@Aryan-Chharia Could you assign it to me.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/souvikpramanikgit/Computer-Vision-Projects/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I am willing to work on this issue (optional)

**Comment by Aryan-Chharia** [comment]
go ahead
