### ISSUE TITLE
Real time object measurement by opencv

### ISSUE THREAD

**Issue by Nikhith221B** [Aryan-Chharia/Computer-Vision-Projects#34]
We will use an A4 paper as our guide and find the width and height of objects placed in this region.
@Aryan-Chharia assign it to me
please look into this issue @c0sm0void  @Vaibhav22p-qw

**Comment by Abhiiesante** [comment]
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted

**Comment by Absk024** [comment]
i would like to contribute @Aryan-Chharia
