### ISSUE TITLE
Pose Detection Project Proposal using OpenCV and Mediapipe

### ISSUE THREAD

**Issue by jaidh01** [Aryan-Chharia/Computer-Vision-Projects#5]
I would like to contribute a Pose Detection project to this repository, utilizing OpenCV and Mediapipe for real-time pose detection. The project will include the following key features:
1. Real-Time Pose Detection: Detect and track human poses in real-time using OpenCV and Mediapipe.

2.Video Recording and Landmark Extraction: Users can record videos and extract pose landmarks, which can then be used to train machine learning models.

3. Applications: This project can be applied in fields such as healthcare, sports, and fitness, aiding in activities like physical therapy, exercise monitoring, and performance analysis.

Request: Kindly assign this issue to me and label it as gssoc24-extd and hacktoberfest.

**Comment by Aryan-Chharia** [comment]
Go Ahead!
