### ISSUE TITLE
Adding contributor section

### ISSUE THREAD

**Issue by shravya312** [Aryan-Chharia/Computer-Vision-Projects#59]

**Comment by alo7lika** [comment]
Contributing Section Overview
The Contributing section of a README is designed to guide potential contributors on how to get involved with the project. It serves as an invitation for developers, testers, and anyone interested to help improve the platform. This section should provide clear and structured instructions, ensuring that contributors can easily understand the process and feel welcomed.

Purpose
Encourage Participation: The section emphasizes the importance of community contributions, highlighting that every input can lead to improvements and innovations.
Provide Guidelines: It outlines specific steps for contributing, ensuring that potential contributors know what is expected and how to proceed.
Promote a Positive Community: By including a Code of Conduct, the section fosters a respectful and collaborative environment.
Key Components
Forking the Project: Instructions for creating a personal copy of the repository to make changes without affecting the original project.
Cloning the Repository: Guidelines for downloading the forked repository to the contributor’s local machine.
Creating a Branch: Emphasizes the importance of working in a separate branch for new features or bug fixes to maintain an organized project structure.
Making Changes: Encourages contributors to implement their features or fixes, adhering to the project's coding style and guidelines.
Testing Changes: Advises contributors to run any tests to ensure that their changes do not introduce new issues.
Committing Changes: Describes how to stage and commit changes with meaningful messages to maintain a clear project history.
Pushing Changes: Instructions for uploading the committed changes back to their forked repository.
Opening a Pull Request: Guidance on submitting a request to merge their changes into the main project, detailing the changes made for review.
Additional Elements
Code of Conduct: A reference to guidelines that promote respectful interaction within the project community.
Issue Reporting: Encourages users to report bugs or suggest improvements, creating an avenue for feedback and collaboration.

assign me this work @Aryan-Chharia .
ADD LABELS hacktoberfest and ggsoc-ext 24
