### ISSUE TITLE
Brain Tumor Detection

### ISSUE THREAD

**Issue by Aditijainnn** [Aryan-Chharia/Computer-Vision-Projects#6]
Brain Tumor MRI Dataset from Kaggle mentioned in the dataset section of the project.
please assign this to me under gssoc ext and hacktober fest

**Comment by Aryan-Chharia** [comment]
@Aditijainnn Can you explain a little more about this project ? Like Approach and Possible future use?

**Comment by JahnaviDhanaSri** [comment]
Hi @Aryan-Chharia 
I would like to take on the Brain Tumor Detection task that utilizes the Brain Tumor MRI dataset from Kaggle. I believe my skills in deep learning and image processing will allow me to effectively contribute to this project. Please consider assigning this task to me under GSSoC and Hacktoberfest.
