### ISSUE TITLE
AI Calculator Using Computer Vision and GenAI

### ISSUE THREAD

**Issue by ananyag309** [Aryan-Chharia/Computer-Vision-Projects#61]
This project creates a gesture-controlled virtual calculator, allowing users to perform basic arithmetic and trigonometric calculations using hand gestures instead of a traditional keyboard or mouse. Users can wave their hands in front of a camera to recognize specific gestures linked to mathematical operations. For trigonometric functions, users can draw shapes (like triangles, squares, circles) to perform operations such as sine, cosine, and tangent calculations based on the shapes they create. An AI component interprets the shapes and executes the corresponding trigonometric operations.

**Comment by Aryan-Chharia** [comment]
@ananyag309 you have pending issue left. Kindly do them first

**Comment by ananyag309** [comment]
yes raised pr just now
