### ISSUE TITLE
Add a CODE_OF_CONDUCT page

### ISSUE THREAD

**Issue by Aryan-Chharia** [Aryan-Chharia/Computer-Vision-Projects#7]
We need to create a Code of Conduct page that outlines the expected behavior and values for contributors participating in this project. This will help ensure a welcoming and inclusive environment where everyone feels respected. It should cover topics like respect, inclusivity, and professionalism.

(Those who are interested, kindly also explain what content are you going to add in this page.)

**Comment by Prakhar29Sharma** [comment]
Hi @Aryan-Chharia, I would like to take this issue
I'll create a CODE_OF_CONDUCT.md file and add content like our pledge, our standards (with example of unexpected behavior) etc. by following standard structure of CODE_OF_CONDUCT.md file.  
reference : [https://www.contributor-covenant.org/version/2/1/code_of_conduct/](url)

Any feedback is welcome!

**Comment by Aryan-Chharia** [comment]
Go Ahead!
