### ISSUE TITLE
Optimize YOLO Object Detection in main.py

### ISSUE THREAD

**Issue by BigBang001** [Aryan-Chharia/Computer-Vision-Projects#70]
### Issue Description
I would like to propose an enhancement for the YOLO object detection implementation in `main.py`. The following changes are intended to improve both the code quality and the performance of the object detection process:

**Proposed Changes:**
- Refactor the code for improved readability and performance.
- Remove hardcoded paths for model weights and configuration files to enhance flexibility.
- Implement error handling for image loading to avoid crashes on incorrect paths.
- Optimize Non-Maximum Suppression (NMS) parameters to enhance detection accuracy.

**Performance Improvements:**
- **Dynamic Paths**: Enables the script to run on different machines without modifications.
- **Error Handling**: Provides user-friendly feedback when loading images fails.
- **NMS Optimization**: Aims to reduce false positives and enhance detection reliability.

**Specific Areas of Optimization:**
- Streamlined image resizing for consistent input dimensions.
- Maximized efficient array operations using NumPy.
- Optimized random color generation for bounding boxes.

**Why These Changes Are Important:**
These optimizations will enhance user experience, improve performance, and adhere to best coding practices, making the project easier for future contributors to maintain and expand upon.

### Request for Assignment
Please assign this issue to me under Hacktoberfest and gssoc-extd.

**Comment by Aryan-Chharia** [comment]
Go Ahead
