### ISSUE TITLE
Add a Contributing page

### ISSUE THREAD

**Issue by Aryan-Chharia** [Aryan-Chharia/Computer-Vision-Projects#8]
A Contributing Guidelines page is necessary to help contributors understand how to get involved with the project. This page should provide instructions for setting up the project, coding standards, and how to submit pull requests, ensuring a smooth contribution process for both newcomers and experienced developers.

(Those who are interested, kindly also explain some points, specific to this repo, that you are going to add.)

**Comment by ananyag309** [comment]
@Aryan-Chharia i will also take help oof other project and will try my best to make it worthy

**Comment by Aryan-Chharia** [comment]
Go Ahead!
