### ISSUE TITLE
Text-to-Image Generator without any API.

### ISSUE THREAD

**Issue by jaidh01** [Aryan-Chharia/Computer-Vision-Projects#82]
Text-to-image generation model which uses Stable Diffusion model to generate Images.
Since, it does not require any API, therefore everything remains on the local system and provide privacy as well.

It would be able to generate images like this: - 

![generated_image](https://github.com/user-attachments/assets/e4532d9f-e161-4b92-b68d-83f72d19d5f7)

**Comment by AtharvSomani** [comment]
Hi i want to work on this project

**Comment by Aryan-Chharia** [comment]
Not needed in computer vision repo

**Comment by Abhiiesante** [comment]
I have an experience in DL, NLP and also in computer vision.
we can perform it by using pre-trained GAN models e.g StyleGAN, BigGAN
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted
