### ISSUE TITLE
Add Defective Captcha Image Recognition

### ISSUE THREAD

**Issue by ananyag309** [Aryan-Chharia/Computer-Vision-Projects#9]
The main purpose of this project is to identify capcha digits from 1-9 even when they're noisy and defected from the dataset Link :- https://www.kaggle.com/datasets/kadenm/noisy-digitbased-captcha-images using various image detection/recognition models and comparing their accuracy.

Project involves the comparative analysis of Five Keras image detection models, namely EfficientNetB1 , ResNet50V2 , InceptionV3 , DenseNet121 and Xception applied to a specific dataset. The dataset consists of annotated images related to a particular domain, and the objectives include training and evaluating these models to compare their accuracy scores and performance metrics. Additionally, exploratory data analysis (EDA) techniques are employed to understand the dataset's characteristics, explore class distributions, detect imbalances, and identify areas for potential improvement. The methodology encompasses data preparation, model training, evaluation, comparative analysis of accuracy and performance metrics, and visualization of EDA insights.

please assing it to me under gssoc ext and hacktober fest

**Comment by Aryan-Chharia** [comment]
Go Ahead!

**Comment by Aryan-Chharia** [comment]
@Niraj1608 go ahead
