### ISSUE TITLE
Dog breed classification using transfer learning.

### ISSUE THREAD

**Issue by jaidh01** [Aryan-Chharia/Computer-Vision-Projects#93]
🔴 Title: Dog breed classification
🔴 Aim: To build a model which is able to classify dog breed.
🔴 Brief Explanation:
Using over 10,000+ images and MobileNetV2 with transfer learning, this model would be able to classifies different dog breeds with impressive accuracy.

Total no of Dog breed it would be able to classify : - 120

**Comment by jaidh01** [comment]
Hi @Aryan-Chharia ,

I hope you're doing well.
After reviewing the complexity of this task, I believe it would be more appropriate to upgrade the label from `Level 1` to `Level 2` . Could you please consider changing the label accordingly?

Thank you for your time!

**Comment by Aryan-Chharia** [comment]
@jaidh01 I will decide after seeing the Pull Request. Make the PR using the template provided. I will decide after seeing the PR. Don't worry about it as of now. It can easily be changed.

**Comment by jaidh01** [comment]
Hi @Aryan-Chharia,

Since the issue and its PR are now closed, could you please consider improvements to the `level` label?

Thank you for your time!
