### ISSUE TITLE
Fashion MNIST for Image Classification

### ISSUE THREAD

**Issue by Lonwwolf14** [Aryan-Chharia/Computer-Vision-Projects#97]
One of the most used MNIST datasets was a database of handwritten images, which contains around 60,000 train and 10,000 test images of handwritten digits from 0 to 9. Inspired by this, they created Fashion MNIST, which classifies clothes. As a result of the large database and all the resources provided by MNIST, you get a high accuracy range from 96-99%.

**Comment by Absk024** [comment]
i would like to contribute @Aryan-Chharia

**Comment by Aryan-Chharia** [comment]
@Absk024 go ahead
