### ISSUE TITLE
Implement Image Transformation using Cycle GAN

### ISSUE THREAD

**Issue by Lonwwolf14** [Aryan-Chharia/Computer-Vision-Projects#98]
### Issue Title:  
**Implement Image Transformation using Cycle GAN**

### Issue Description:  
In this task, the goal is to transform images into different forms using **Cycle GAN**, a type of Generative Adversarial Network (GAN). Unlike standard GANs, which can be difficult to train for image transformations, Cycle GAN creates a cycle of transformations to generate realistic outputs. This approach allows for transforming real images into graphical representations and vice versa.

The Cycle GAN architecture consists of two competing neural networks:
- The **generator**, which creates new image samples.
- The **discriminator**, which judges whether the generated images are real or fake.

The networks work together to improve over time, making Cycle GANs a continuous improvement model.

The task involves implementing this architecture to transform images, with the end goal being to produce high-quality artwork from real images, similar to how translation works in language models. For instance, just as translating English to German and back to English should return the original phrase, Cycle GAN tries to generate an image that can be transformed back to its original form.

This issue focuses on:
- Creating the Cycle GAN model.
- Training it on the chosen dataset.
- Ensuring the **cycle-consistency loss** for effective image transformation.

**Comment by Aryan-Chharia** [comment]
Can you include images for better understanding of the project?
